In [1]:
import numpy as np

In [9]:
import numpy as np
name_str='input100sample{}std_w1{}std_w2{}.npz'

w2_std=0.9
w1_std_list=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
sample_index_list = range(50,150,10)

for sample_index in sample_index_list:
    for w1_std in w1_std_list:
        name_now=name_str.format(sample_index, w1_std,w2_std)
        data=np.load(name_now)

        print(data['std_w1_list'])
        

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
[0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
[0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8]
[0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
[0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
[0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
[0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8]
[0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
[0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
[0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
[0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0

FileNotFoundError: [Errno 2] No such file or directory: 'input100sample100std_w10.3std_w20.9.npz'